# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/RDF-ACL/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires "Test::More 0.61" ;
	:requires "Data::UUID" ;
	:requires "Error" ;
	:requires "RDF::TrineX::Functions" ;
	:requires "RDF::Query" ;
	:requires "RDF::Query::Client" ;
	:requires "Scalar::Util" ;
	:requires "URI" .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/RDF/ACL.pm" .
